### ISSUE TITLE
Mettre à jour la traduction en anglais

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#113]
@yoanmalie si jamais tu as du temps à perdre :smiling_imp:

**Comment by remijean** [comment]
Todolist : 
Trier textes par ordre alphabétique
Checker les textes des modules
Traduire les textes en js
Checker qu'il ne reste pas des anciens texte non utilisés

**Comment by yoanmalie** [comment]
Hello,
j'avais pas vu la mention mais j'avais commencé à traduire.
Cest un peu relou à trouver les chaines supprimées, il faudrait les noter quand tu les supprime du core.

Pour le moment j'ai fais le core, les modules arrivent bientôt !

**Comment by remijean** [comment]
@yoanmalie mince entre temps j'ai corrigé l'ensemble des textes :/

**Comment by remijean** [comment]
@yoanmalie tu as fais tes modifs depuis quelle branche ? Sur la dev j'avais déjà ce commit : 73d61226f2e4d083f4557ad243c312d7cb099d05

**Comment by yoanmalie** [comment]
Depuis dev mais je n'avais pas remarqué, (ni fetch du coup) tes changements, notamment celui-là : 1e51ec9c93c76d5c560d6b249a2a3ba0a5ff2c73

L'issue étant encore ouvert je me suis dit, bon allez, je le fais :smile: 

![facepalm](https://cloud.githubusercontent.com/assets/3357171/14790917/c573b4a2-0b13-11e6-986b-105fe86c6779.gif)

**Comment by remijean** [comment]
@yoanmalie Ah shiiiiiit ! Je vais quand même checker si je peux récupérer quelque chose :mag:

**Comment by remijean** [comment]
@yoanmalie bon bah en final j'avais déjà bien corrigé :santa:
