### ISSUE TITLE
Créer un module player mp3

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#115]
http://jplayer.org/

http://forum.zwiicms.com/viewtopic.php?f=5&t=11&p=595#p595

**Comment by lechti64** [comment]
j'ai lu sur le forum de soutien , pour le player çà risque d'alourdir un peu le cms mais c'est un petit gadget pas mal pour ceux qui en auront utilité ( mais une intégration de player peut se faire aussi directement dans un post du cms en utilisant l'editeur en code source et recopier ensuite sur une page dédiée .
Pour le mettre sur un site entier Zwiicms , il faudra prévoir alors la possibilité d'un bouton pour couper le player ( tous n'aime pas la musique sur un site quand ils naviguent )

La solution que tu avait donné rémi sur le forum était bien meilleur , un petit tuto pour intégrer un player , un lien pour le télécharger et hop , le tour était joué hahahahaha .
Les gens qui installent le cms le font directement sur leur serveur d'hébergement ,  alors ils peuvent bien aussi envoyer dans le data les fichiers pour faire fonctionner un player sur leur site .

**Comment by remijean** [comment]
Non ça n'alourdira pas le cms car je vais l'ajouter sous forme de module, et chaque module peut être supprimé du cms en supprimant simplement son dossier dans le dossier modules :+1: 

Le player sera rattaché à une page comme le module de news par exemple, le module est super pratique pour un mec qui veut créer une webradio par exemple, non ?

**Comment by lechti64** [comment]
Va pour cette forme de module , ça peut l'faire si tu arrives à trouver le bon player .
Et un module qui ferait steam de playliste et video en m^me temps , tu crois pas que ce serait complet pour tout les gouts ?

**Comment by remijean** [comment]
Abandonné.
