### ISSUE TITLE
Bug d'affichage avec le capcha

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#120]
Le label du capcha s'affiche sur 2 ligne

**Comment by remijean** [comment]
En fonction de la police ?

**Comment by yoanmalie** [comment]
Sur 2 lignes selon la police, 8 selon le syndicat.

Et si tu agrandis la colonne, en passant de `col3` à `col4` ?

**Comment by remijean** [comment]
8 selon le syndicat ?

Je pense que c'est la seule solution, le problème est aussi présent avec la largeur petite :/

**Comment by remijean** [comment]
Moche si > 3, je ferme le bug je verrais pour changer les polices disponibles
