### ISSUE TITLE
Bandeau de cookie pour l'admin

### ISSUE THREAD

**Issue by yoanmalie** [remijean/ZwiiCMS#123]
Hello,

Il ne serait pas plus judicieux d'enlever le bandeau d’acception de cookies pour la partie admin ?
D'autant plus qu'il n'y à pas le tracker de GA activé dans l'administration. Et bonus, ça ne gêne pas pour accéder au menu...

Edit: Ah bah non, GA est même activé sur l'admin :smile: !

**Comment by remijean** [comment]
@yoanmalie je pense pas que ce soit un vrai problème, le message GA disparaît après avoir cliqué sur le bouton OK, puis yes j'ai ajouté GA dans l'admin car des utilisateurs ne comprenaient pas pourquoi GA affichait 0 personne en ligne alors qu'il était sur leur site.

**Comment by remijean** [comment]
@yoanmalie pas d'avis ? Je ferme du coup :wink:
