### ISSUE TITLE
Choisir la position du module dans la page

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#125]
Au dessus
En dessous
Et pourquoi pas mode libre avec une aide qui demande d'ajouter une balise type [SHOW_MODULE] dans la page afin de l'afficher

**Comment by lechti64** [comment]
au dessus ou ne dessous ce sera facile ( positionnement par rapport au texte écrit dans la page ) mais en position libre , ce sera plus coton car il faudra se baser alors sur le nombre de lignes écrites dans la page où devra être placé le module galerie et je ne pense pas que ce soit possible d'appeler le module galerie depuis tinymce ( avec la fonction SHOW_MODULE ) à moins de l'incorporer à tiny comme un plugin dépendant de lui ( comme pour le plugin youtube de tiny ou celui des img )

**Comment by remijean** [comment]
@lechti64 j'ai développé une solution simple, il suffit juste de sélectionner position libre et d'écrire [MODULE] dans le contenu de la page depuis tiny :smile:
