### ISSUE TITLE
Impossible de changer le design des tableaux

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#132]
http://forum.zwiicms.com/viewtopic.php?f=5&t=170

**Comment by lechti64** [comment]
le désign des tableaux et de leur cellules se gère directement depuis l'interface de tinymce , sur le forum de soutien j'ai donné la solution au membre qui en faisait la demande et pas besoin vraiement de modifier le cms pour ce faire .
Un tableau peux avoir un fond de couleur de m^me que des bordure de couleurs
Les cellules d'un tableau peuvent elles aussi avoir leur propre fond de couleur et aussi leurs propres bordures colorée .

Quand les gens crée un tableau dans un zwiicms , ils restent généralement sur la page de réglage du tableau ( nombre de cellules , couleur de fond du tableau etc ..) mais il ne pensent pas que quand le tout est créé , il suffit ensuite de cliquer sur chaque cellule ( dans la page où s'affiche le tableau avant enregistrement final de celle ci ) pour les personnaliser  leur tour ....

Sur le forum , trois réponses au dessu tu aurasis vu que tout ceci était bien expliqué et m^me imagé ...
voir ici et lire les deux post postés l'un à la suite de l'autre : [http://forum.zwiicms.com/viewtopic.php?t=170&p=1348#p1338](url)

**Comment by lechti64** [comment]
http://forum.zwiicms.com/viewtopic.php?t=170&p=1348#p1338

**Comment by remijean** [comment]
@lechti64 j'ai déjà pris le temps de lire tes msgs mais il y a quand même un bug : il est impossible de modifier la couleur de fond du tableau il faut obligatoirement changer la couleur des lignes ou des cellules donc je ne ferme pas :).

**Comment by remijean** [comment]
Corrigé avec la 8.0.1
