### ISSUE TITLE
Quelques Améliorations à Ajouter (Certaines SONT FACILES & RAPIDES à FAIRE!)

### ISSUE THREAD

**Issue by MehdiBmm** [remijean/ZwiiCMS#137]
Bonjour Rémi.

J'ai utiliser ZwiiCms et j'ai très bien apprécié. Voilà mon idée globale, sais tu que comme tu site ne demande pas de BD SQL, il serais niquel pour faire des landing page? (je suppose que tu connais le mot, on dit squeeze page aussi, la oû on demande l'émail et le nom d'une personne pour l'avoir dans une liste d'émail marketing etc...) BREF voilà, regarde les améliorations ci-dessous et applique les!

Pour Les Pages (Spécifique à chaque page) : 

- Permettre d'enlever le header (bannière).
- Permettre d'enlever le menu.
- Permettre d'enlever le nom de la page.
- Permettre d'enlever les liens en bas (Plan, Administration...).
- Permettre d'enlever les liens sociaux (Facebook, Twitter....).
- Permettre d'enlever le Powered by...

Pour La Mise En Page :
-Ajouter de nouveaux type d'ombres au site.
-Permettre à l'utilisateur de choisir la taille de la police (De 8 à 50px serais bien).
-Permettre l'ajout d'ombres aux textes (surtout les h1, h2....).

Quelques Nouvelles Options :
-Permettre l'ajout d'un bouton avec "action" et "lien" personnalisé.

Tous ça parce que comme j'ai dit, ton CMS est PARFAIT pour une landing page seulement il manque quelques trucs importants.

**Comment by remijean** [comment]
@MehdiBmm 

Si je comprends bien tu voudrais que tes modifs puissent s'appliquer par page et non directement à toutes les pages du site ?

Si je reprends point par point  : 

- Permettre d'enlever le header (bannière).
Déjà possible juste pour l'ensemble du site

- Permettre d'enlever le menu.
Déjà possible juste pour l'ensemble du site

- Permettre d'enlever le nom de la page.
Déjà possible

- Permettre d'enlever les liens en bas (Plan, Administration...).
Arrivera dans la v8 pour l'ensemble du site et non page par page

- Permettre d'enlever les liens sociaux (Facebook, Twitter....).
Déjà possible pour l'ensemble du site

- Permettre d'enlever le Powered by...
Possible en modifiant le layout mais je ne veux pas créer de fonctionnalité pour l'enlever depuis l'admin (faut bien se faire connaitre 😄 )

-Ajouter de nouveaux type d'ombres au site.
-Permettre à l'utilisateur de choisir la taille de la police (De 8 à 50px serais bien).
-Permettre l'ajout d'ombres aux textes (surtout les h1, h2....).
Je vais conserver tes idées de côtés, je compte refaire une passe sur la personnalisation mais j'ai quelques sujets avant

-Permettre l'ajout d'un bouton avec "action" et "lien" personnalisé.
Tu peux ajouter des liens avec l'éditeur de texte, pour les boutons ce n'est pas prévu pour l'instant car ça demanderais trop de modifs ou alors le dev d'un widget tinyMCE.

Pour l'aspect modifs page par page je comprends le besoin pour des landing pages, mais cela demanderais une restructuration complète de la base et de l'administration... Je suis actuellement entrain de développer la version 8 qui est déjà une refonte de la structure du CMS afin de le rendre plus flexible mais je ne l'ai pas prévu pour fonctionner page par page et si je voulais le faie ça me m'obligerais à repartir de nouveau de 0, c'est une approche très intéressante mais je ne pense pas pouvoir l'appliquer avant un petit bout de temps 😞 .

**Comment by MehdiBmm** [comment]
D'accord! Mais voilà ZwiiCms c'est vraiment le top pour des landing page et je m'en rend compte.

En effet j'ai fais ma landing page comme tu a dit (pas de bannière, ni de titre etc....) mais ça s'applique à toutes les pages.

Dommage que cela demande une re-structure complète mais bon ZwiiCms à du temps pour grandir :D

**Comment by MehdiBmm** [comment]
Attached is my files

**Comment by lechti64** [comment]
Je trouve pour ma part contraignant pour le développeur de devoir re-programmer une fonction applicable déjà actuellement ( effacement de toute publicité sous forme de bannière , lien de bas de page etc faisant référence à un site construit avec le cms zwii  ) pour proposer fonction de  page vierge en somme et qui ne servirait que pour un genre de marketing et pour un utilisiteur gestionnaire de devoir ensuite aller dans son panneau adminitsratif gérer pour chaque page qu'il crée l'affichage ou non de sa propre bannière , l'affichage ou non de ses liens de bas de page ou réseaux sociaux etc ...cela deviendroit vite contraignant pour l'utilisateur final du cms alors que si l'on veut créer ce style de page , il suffit de le faire en simple redirection et d'y inclure un propre css personnalisé de m^me que sa propre architecture de page vierge .
beaucoup de nos utilisteurs utilisent ce cms dans le cadre de simple site web , voir de site collaboratif ou professionels ( un peu comme une vitrine ) mais bien peu l'utilisent à des fins où toutes traces de leur identité ou lien web qui leur sont utiles doivent être effacées pour garantir un " anonyma " lorsque l'on arrive sur une page où se trouve un formulaire à remplir pour servir à une quelconque campagne de " récolte " de quoi que ce soit ;

Moi je suis franchement de l'avis de Rémi et il y a bien plus important actuellement à faire dans la nouvelle version V8 qui devrait sortir la prochaine année et pas mal de fonctions qui fonctionnent déjà parfaitement ce jour au point de devoir revoir la copie en entier pour une simple fonction de d'écrasement de page ou de redirection de page ...

**Comment by remijean** [comment]
Traité dans la v8, sauf "modifier la taille de la police" qui arrivera bientôt.
