### ISSUE TITLE
Couleur du texte du footer et menu

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#141]
Si la couleur de fond du footer ou du menu est à 100% transparente = couleur de police sombre.

Problème si : 

- Couleur du fond sombre
- Image
- http://forum.zwiicms.com/index.php?/topic/290-roger-mes-retours-de-la-800-b%C3%AAta-02/&do=findComment&comment=2817

Solutions : 

- Checker la couleur du fond du site lorsque la transparence est à 100%
- Autoriser le changement des couleurs de textes des deux éléments
- Bloquer la transparence à 90% max
- Ignorer si peu de uses cases

À faire : 

- Trouver des uses cases pour choisir la solution optimale

**Comment by lechti64** [comment]
Vraiment c'est attendu avec ferveur cette possibilité de ne pas avoir la couleur des texte s'assombrir lorsque l'on utilise la transparence du fond dans le menu oiu dans le footer du cms

Donc la meilleur solution est de permettre aussi le changement des couleurs de texte pour ces deux éléments là ( menu et footer )

**Comment by remijean** [comment]
@lechti64 j’étudiais la question après le dev de la 8.0.0, j'ai aussi ajouté une solution : "Bloquer la transparence à 90% max".

Je vais étudier les possibilités au moment voulu, merci pour la remontée.

**Comment by lechti64** [comment]
**Surtout ne pas bloquer ni limiter la transparence !!!!!** , c'est important de pouvoir choisir le taux de transparence dans le picker entre 0% ( aucune transparence ) et 100% ( transparence totale )

**Comment by remijean** [comment]
Ajouté dans la 8.2.0
