### ISSUE TITLE
Non réception des mails

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#142]
Certains webmails ne reçoivent pas les mails : 

FREE
YAHOO

http://forum.zwiicms.com/index.php?/topic/333-module-form-ne-fonctionne-pas/

**Comment by lechti64** [comment]
Rémi , je pense que **ce n'est pas un problème du à Free ou Yahoo** puisque chez moi ( 1&1 ) si j'aimis dans un zwii une adresse du style " tartampion@laposte.net " et bien je ne reçois pas non plus les mails ;
Le probléme ne vient pas donc du fournisseur qui héberge nos fichier mais bien de l'adresse mail que ernetre l'admin dans un zwii pour être contacté

J'ai essayé la chose depuis mes espaces chez
**Free
1&1**  

Chez mes deux fournisseurs là , toutes les autres adresses mail marchent sans problème
