### ISSUE TITLE
Ortographe: Petite correction mineure

### ISSUE THREAD

**Issue by seigneurfuo** [remijean/ZwiiCMS#143]
Bonjour, dans la fenetre d'envoi de fichiers, on peut lire le texte suivant: 
> Glissez les fichier ici pour les ajouter
![image](https://cloud.githubusercontent.com/assets/20669563/24364205/4d90baf4-1312-11e7-8d4a-ee878b924889.png)
Un "s" est manquant à la fin de "fichier".

Autrement, très bon projet ! Bravo !

**Comment by remijean** [comment]
@seigneurfuo merci pour l'info je vais corriger ça dans la prochaine version ! Et merci pour les encouragements 😄 .
