### ISSUE TITLE
Remplacer RFM par un gestionnaire de fichiers maison

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#151]

**Comment by lechti64** [comment]
sacré chantier que celui ci , on va s'y ateler

**Comment by remijean** [comment]
Je vais livrer quelque chose de bien plus simple que RFM, je vais garder les fonctionnalités principales. Pour les autres elles viendront avec le temps. Puis pour les impatients il suffira de créer un plugin RFM ou elFinder 😉

**Comment by lechti64** [comment]
Prends le temps car nous on a une sacrée surprise pour toi et là tu en tomberas des nues . Dans le bon sens ça va et tu auras je pense les premiers topics pour çà sur le forum , donc moins de stress en attendant pour toi créer ce gestionnaire indépendant

**Comment by remijean** [comment]
Abandonné.
