### ISSUE TITLE
Module forum (?)

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#157]
Voir si pas trop colossale à mettre en place.

**Comment by simon511000** [comment]
WoW, un forum sans base de données... Je te souhaite bonne chance @remijean

**Comment by remijean** [comment]
@simon511000 héhé yes, c'est encore un projet, je ne le mettrais pas en place si c'est trop compliquer à mettre en place (niveau structure des données).

**Comment by remijean** [comment]
Abandonné
