### ISSUE TITLE
Rendre plus clair l'édition de thème

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#159]
> Dans la zone admin le message "Cliquez sur une zone....". Je suis sans doute idiot mais j'ai mis une heure à comprendre qu'il fallait cliquer sur menu (par exemple) pour modifier le menu, sur un titre pour modifier les titres !. Bref je suppose que d'autres vont patauger comme moi sur ce point important ou je suis bon pour l'asile ;-) Suggestion : mettre Cliquez sur une zone (menu, bandeau, titre...) etc....

http://forum.zwiicms.com/index.php?/topic/391-dan-le-retour-%C3%A0-propos-de-la-810/

**Comment by lechti64** [comment]
Et y'a qu'un idiot qui peut reporter ce genre de message , tout les autres utilisteurs ont depuis longtemps pigé le trucs eux  et bien d'autres aussi ...

**Comment by remijean** [comment]
Hum je ne trouve pas idiot de préciser entre parenthèse à quoi correspond une zone, le terme zone n'est pas très parlant 😄

**Comment by lechti64** [comment]
Il le sera une fois que tu auras fait ta doc sur l'utisation du zwii , ou alors bien plus simple tu renommes " Zone " en "Zones caché" , pourquoi faire simple quand on peut faire compliqué , et faut vraiment être idiot quand on est dans les paramétrages du design pour pas se douter que chaque bouton sur une page à un rapport justement avec le réglage appellé dans la barre asmin du zwii 😄
