### ISSUE TITLE
Ne plus afficher mot de passe dans mail

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#163]
Pas top niveau sécurité

**Comment by lechti64** [comment]
Ok pour ne plus envoyer le mot de passee du compte en dur dans un mail mais surtout ne pas supprimer la confirmation envoyée lors de la création du zwii avec au minimum dedans l'adresse du site et le nom de login de l'admi ...;
Bien entendu conserver la possibilité en entrant son nom de login se faire envoyer sur son mail le m^me  lien qui permet de changer son mot de passe , ça c'est vraiment le minimum quand on s'inscrit quelque part
