### ISSUE TITLE
Erreur fatale si une page parent n'a aucun enfant visible

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#168]
http://forum.zwiicms.com/index.php?/topic/420-erreur-404/

Reproduire le bug et le corriger.

**Comment by lechti64** [comment]
aprés une  petite enquête sur ce bug ( qui n'en est pas un ) , je suis certain à 100% que zwii n'est aucunement responsable de cette erreur page 404, démonstration en a été faite sur le forum de soutien du cms ( images et liens à l'appui , pour reproduire cette erreur c'est tout simple.... )

**Comment by remijean** [comment]
Non reproductible
