### ISSUE TITLE
tinymce

### ISSUE THREAD

**Issue by simon511000** [remijean/ZwiiCMS#181]
tinymce ne fonctionne plus du tout sur iPad

**Comment by simon511000** [comment]
![](https://framapic.org/7lK99iO03d1M/ta3x75ji86QR)

**Comment by remijean** [comment]
Il s'agit du mode mobile de tinymce, il faut cliquer sur le bloc ça ouvrira le mode édition mobile.

**Comment by simon511000** [comment]
non, lorsque je clique sur le bloc, la page devient blanche ;)

**Comment by fredtempez** [comment]
Je confirme le problème, je regarderai la configuration de Tinymce demain.

**Comment by remijean** [comment]
@fredtempez, je te laisse regarder car je n'ai pas d'ipad pour tester et sur mon mobile ça fonctionne :

![screenshot_20180327-235524_samsung internet](https://user-images.githubusercontent.com/4329231/37997203-930ac282-321a-11e8-9d08-d40fbe8145de.jpg)

**Comment by fredtempez** [comment]
A priori le support est prévu jusqu'à IOS 10 et on est à 11. Des utilisateurs vont remonter des pbs, je vais tester de passer la version mobile en version cloud pour voir si ça règle le problème.
En attendant il suffit de basculer la page en version ordinateur pour retrouver l'éditeur.

**Comment by fredtempez** [comment]
La compatibilité est assurée jusque IOS 10 pour la version courante de thème mobile, il faut attendre une évolution de l'éditeur. En attendant , passer la page en mode Ordinateur sur iPad.
[Page TinyMCE Mobile](https://www.tinymce.com/docs/mobile/ )
