### ISSUE TITLE
English

### ISSUE THREAD

**Issue by iskono** [remijean/ZwiiCMS#40]
pouvez-vous faire une version d'anglaise?

**Comment by remijean** [comment]
@iskono Bonjour, oui je travaille actuellement sur la version anglaise pour la prochaine mise à jour de ZwiiCMS.

**Comment by iskono** [comment]
essaie de traduire, mais le fichier de base est un peu compliquée

**Comment by remijean** [comment]
@iskono The English translation is provided for ZwiiCMS 7.2.0 due out on October 1 :+1: .

**Comment by iskono** [comment]
Many thanks , been using your cms from ages .
Thanks
