### ISSUE TITLE
Ajouter Google Analitycs

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#55]
Ajouter une option. (entrer uid du compte)

**Comment by yoanmalie** [comment]
Tu le veux inclu dans le core ou en tant que module ? J'ai un PR prêt pour la première option.

**Comment by remijean** [comment]
Yes dans le core :)

**Comment by yoanmalie** [comment]
Ok je te laisse regarder mon PR #83 si ça te convient. J'ai essayé... :stuck_out_tongue_winking_eye:
