### ISSUE TITLE
Première News

### ISSUE THREAD

**Issue by MAYdev** [remijean/ZwiiCMS#6]
# Explication :
A la création d'une news, une page blanche avec des erreurs PHP apparait.

![erreur news zwii](http://img4.hostingpics.net/pics/840189erreurzwiinews.png)

# Comment reproduire le bug :
:warning: Il ne faut jamais avoir créer de news auparavant, Remettre le fichier data.json par défaut.

Créer une page en y ajoutant le module "gestionnaire de news" puis enregistrer. Cliquer sur le bouton "administrer" puis créer une News en laissant les champs vide.

**Comment by remijean** [comment]
@MAYdev Hum un vilain bug !
