### ISSUE TITLE
Le titre du site bug en responsive

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#70]
Trouver une alternative au line height

**Comment by yoanmalie** [comment]
Hello, 
J'allais proposer un petit PR pour corriger ça mais je voulais savoir quelle version minimale d'IE tu respecte dans ce thème par défaut ?

**Comment by remijean** [comment]
@yoanmalie cool ! IE9+ normalement depuis http://www.generation-nt.com/microsoft-abandonne-internet-explorer-8-9-10-12-janvier-actualite-1923433.html je ne cherche plus à rendre le cms compatible en dessous

**Comment by remijean** [comment]
@yoanmalie j'ai mergé ton correctif, je vais apporté une petite modif au niveau du css : 

```
#header {
	height: 160px;
	line-height: 160px;
	text-align: center;
	background-position: center;
	background-repeat: no-repeat;
}
#header h1 {
	display: inline-block;
	vertical-align: middle;
	margin: 0;
	font-size: 1.8em;
	line-height: 1.2;
	color: #FFF;
}
```

**Comment by yoanmalie** [comment]
Bien vu avec vertical-align :+1: C'est moins risqué que ma solution.
