### ISSUE TITLE
Class themeImage de body

### ISSUE THREAD

**Issue by yoanmalie** [remijean/ZwiiCMS#72]
Lorsqu'on choisit d'avoir une image en background du header, le titre devrait être caché, ça fonctionne en prévisualisation en admin grâce au JS mais pas lorsqu'on sauvegarde, à cause de la classe généré, il y a un bug.
On se retrouve avec l'url de l'image au lieu de _themeImage_
![image](https://cloud.githubusercontent.com/assets/3357171/12922613/77f22dfa-cf52-11e5-9dcb-dbaf0ef89480.png)

**Comment by remijean** [comment]
@yoanmalie oups je l'ai corrigé mais j'ai oublié d'indiquer le fix dans le texte du commit, du coup je ferme manuellement !
