### ISSUE TITLE
Trouver comment faire ressortir les onglets

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#79]

**Comment by remijean** [comment]
L'utilisateur ne comprend pas qu'il s'agit d'onglet.

**Comment by yoanmalie** [comment]
J'avais pas vu cet issue que je me suis dis pareil et j'ai cherché une solution simple et rapide.

Si c'est bien ceux de l'admin "Configuration générale, configuration avancée, personnalisation du thème", sans trop faire de modification je propose les onglets centré et une marge plus grande en haut et en bas, genre comme ça :
![image](https://cloud.githubusercontent.com/assets/3357171/13197913/c100bff0-d7fb-11e5-9a86-55c2a9615a1b.png)
C'est déjà un peu plus mis en avant.

**Comment by remijean** [comment]
Hello, mouais je suis pas convaincu les marges sont un peu trop grosses, non ?

**Comment by yoanmalie** [comment]
Juste en les réduisant ça irait ou alors faut un peu plus pousser la recherche ?
J'avais mis 50px, la j'ai test avec 20:
![image](https://cloud.githubusercontent.com/assets/3357171/13204426/0fca7f98-d8d0-11e5-93c3-3c8d4caa6b54.png)

**Comment by remijean** [comment]
Bah je trouve l'espace entre configuration et titre du site un peu moche, de base j'avais créé les onglets avec ce style pour reprendre le design des sous-titres. Je ne sais pas trop comment faire ressortir les onglets sans casser avec l'aspect épuré mais si tu as des idées je suis preneur ! :D

**Comment by yoanmalie** [comment]
C'est pas faux pour l'espace entre configuration et le titre. J'essaierais quelques trucs à l'occasion, je re posterais ici.

**Comment by remijean** [comment]
En final après plusieurs tests un new user comprend rapidement, je ferme.
