### ISSUE TITLE
Ajouter un lien Back To Top

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#81]

**Comment by lechti64** [comment]
une petite idée à creuser et tester ( fonctionnelle dans le cms en version4.4.4 )

dans le layout.html ( là où on veut que le top revienne )
`<p id="back-to-top"><a href="#top"><span></span></a></p>`
toujours dans le layout avant la fin du body
`<script type="text/javascript">
$(document).ready(function(){
$("#back-to-top").hide();
$(function () {
$(window).scroll(function(){
if ($(window).scrollTop()>550){
$("#back-to-top").fadeIn(1500);
}
else
{
$("#back-to-top").fadeOut(1500);
}
});
//back to top
$("#back-to-top").click(function(){
$('body,html').animate({scrollTop:0},1000);
return false;
});
});
});
</script>`
(paramétrer la hauteur ou l'on veut voir apparaite l'image du scroll et le temps d'animation pour l'apparition de cette image ici
`if ($(window).scrollTop()>550){
$("#back-to-top").fadeIn(1500);
}`

Ajouter dans le custom.css ceci
`#back-to-top a{
text-align:center;
text-decoration:none;
color:#d1d1d1;
display:block;
width:80px;
/*??CSS3??transition?????????????????*/
-moz-transition:color 1s;
-webkit-transition:color 1s;
-o-transition:color 1s;
}
#back-to-top a:hover{
color:#979797;
}
#back-to-top a span{
background:#d1d1d1;
border-radius:6px;
display:block;
height:30px;
width:30px;
background:#d1d1d1 url(images/arrow-up.png) no-repeat center center;
margin-bottom:5px;
-moz-transition:background 1s;
-webkit-transition:background 1s;
-o-transition:background 1s;
}
#back-to-top a:hover span{
background:#979797 url(images/arrow-up.png) no-repeat center center;
}`
Mettre l'image représentant une flèche vers le haut dans un dossier image ou ailleurs et renseigner le customme css ici
`background:#d1d1d1 url(images/arrow-up.png) no-repeat center center;`
Bien entendu le css ci dessus est celui qui est en fonction sur mon site de test alors changer les couleurs ou enelever le " trop plein en codage " pour avoir un Back to Top basique .

**Comment by remijean** [comment]
Merci je vais l'intégrer, pas maintenant j'ai trop à faire avec les pages parents mais je le prévois :+1:

**Comment by remijean** [comment]
Oups j'ai oublié d'ajouter le fix dans le commit, je ferme car fonction ajoutée dans la version 7.5.0.

**Comment by lechti64** [comment]
bon boulot Remi , je vois de suite avec la 7.5.0 , je suis certain que tu as bien fais les choses .
