### ISSUE TITLE
Menu vertical

### ISSUE THREAD

**Issue by finkiki** [remijean/ZwiiCMS#84]
J'essaye d'ajouter un menu vertical via une checkbox. Donc j'ai bien ajouter ma checkbox dans le core.php et mon theme dans le css ( menu li -> display:block + décaler le container ) mais ma checkbox n'a aucun effet, mon theme n'est pas pris en compte. Je vois pas où ça coince. Tu as une idée ?

**Comment by remijean** [comment]
Alors si je comprend tu veux afficher côté public un menu vertical en cliquant sur une checkbox ? Ou permettre d'afficher ou non un menu vertical depuis l'admin en cliquant sur une checkbox ?

**Comment by remijean** [comment]
@finkiki bon pas de rep depuis bientôt 15 jours, je ferme :wink: .
