### ISSUE TITLE
Liste des modules non traduit

### ISSUE THREAD

**Issue by yoanmalie** [remijean/ZwiiCMS#87]
Salut,
Pendant que je touche à la traduction, j'ai pu voir que le champs select pour la liste des modules n'est pas traduit.
![image](https://cloud.githubusercontent.com/assets/3357171/13269430/ed692684-da87-11e5-9a2c-976211e80364.png)

**Comment by remijean** [comment]
Yes je le connais mais je n'ai pas cherché de solution, en gros la traduction du module est importée dans une page qui utilise le dit module et pas avant du coup dans config tu n'as pas les traductions :-1: .

**Comment by lechti64** [comment]
Au cas ou ce bug serait toujours d'actualité et pas marqué résolut , dans la dernière version du cms moi j'ai bien Aucun module module qui s'affiche dans la boite de dialogue pour choisir un module à incorporé à une page .

sa traduction en français se situe dans le core.php ( 1ere ligne si dessous )
`			template::select('module', helper::listModules('Aucun module'), [
				'label' => 'Inclure le module',
				'help' => 'En cas de changement de module, les donnÃ©es du module prÃ©cÃ©dent seront supprimÃ©es.',
				'selected' => $this->getData(['pages', $this->getUrl(0), 'module']),
				'col' => 10
			]).`
Et pour la trad en anglais , situé dans le fichier lang en_EN.json à la ligne 23 de celui ci 
`	"Aucun module": "No module",`

Je précise que j'utilise la version 7.4.4 de Zwiicms .
Résolu ou pas ce bug qui date de février ?

**Comment by remijean** [comment]
Non le problème est différent : le nom des modules ne sont pas traduits en anglais dans le champ de sélection, je ne l'ai toujours pas corrigé car je n'ai pas de solution pour le moment

**Comment by remijean** [comment]
Corrigé avec la version 8.

**Comment by lechti64** [comment]
Comme quoi avec de la patience bin on arrive à faire de grande choses et je peux dire que cette V8 est du tonnerre , une vraie réussite Rémi ;
Par contre puisque l'on parle de traduction faudra que ceux qui les écrivent en anglais les articles dans un Zwii et bien pour ceux qui le liront le Zwii en version anglaise , pas évident s'il ne pigent pas un mot de cette langue là .
