### ISSUE TITLE
Traduction du site côté user

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#89]
Multi json ?

**Comment by lechti64** [comment]
une solution : un traducteur automatique et pas besoin de modifier quoi que ce soit dans l'architecture  de base . J'ai mis la solution sur le forum de Ziicms , peut être cela te soulagera il de cette tache là .
Fonctionnel à 100% chez moi

**Comment by remijean** [comment]
Je ne suis pas top fan des trads google, je préfère contrôler le contenu de mon site plutôt que de laisser Google le traduire avec des incohérences, puis la plus part des gens utilisent des navigateurs modernes qui intègres des plugins avec cette fonctionnalité.

**Comment by remijean** [comment]
Plus d'actualité pour le moment.
