### ISSUE TITLE
Problème d'ajout d'image avec TinyMCE

### ISSUE THREAD

**Issue by remijean** [remijean/ZwiiCMS#96]
Ne fonctionne pas si l'URL rewriting est activée.

**Comment by lechti64** [comment]
pour ma part , je me sers de la fontion " Gestionnaire de fichiers " de Zii , importe mes images et entre l'url de l'image ensuite dans TinyMCE ( URL rewriting activé chez moi ) , ou je met direct l'adresse de l'image qui se trouve déjà sur le web , çà fonctionne bien dans ma version 4.4.4 de Ziicms .
Je viens de refaire le test à l'instant ( entrer une image dans le source de l'image de la boite de dialogue de Tiny et il prend bien l'url de l'image prise sur le web et l'affiche correctement dans le site ZiiCMS  ensuite dans le mode public . 

Je n'ai pas ce bug

**Comment by remijean** [comment]
Tu oublies toujours le W de zWii :)

Sinon j'ai réussi à reproduire le bug et à le corriger : https://github.com/remijean/ZwiiCMS/commit/d748dcc2d02eb3a7471eff8bab4d50fcb3ba42a0
